pool:
  name: 'dev-pool'

stages:
- stage: Deploy
  jobs:
  - job: DeployMongoDB
    displayName: 'Deploy MongoDB to Kubernetes Namespace three-tier'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8sconnection'
        azureResourceGroup: 'devepos1-env'
        kubernetesCluster: 'devepos1-cluster'
        namespace: 'three-tier'
        command: 'apply'
        arguments: '-f DB/database.yml'
      displayName: 'Deploy MongoDB to Kubernetes'